# Generated by Django 3.2.3 on 2021-07-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='listing',
            new_name='listing_title',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='messgae',
            new_name='message',
        ),
    ]
